export const GETEMPLOYERBYID_SUCCESS = 'Employer/GETEMPLOYERBYID_SUCCESS';
export const GETEMPLOYERBYID_FAILURE = 'Employer/GETEMPLOYERBYID_FAILURE';

export const GETEMPLOYER_SUCCESS = 'Employer/GETEMPLOYER_SUCCESS';
export const GETEMPLOYER_FAILURE = 'Employer/GETEMPLOYER_FAILURE';

export const GETEMPLOYEE_SUCCESS = 'Employer/GETEMPLOYEE_SUCCESS';
export const GETEMPLOYEE_FAILURE = 'Employer/GETEMPLOYEE_FAILURE';

export const DELETEEMPLOYEE_SUCCESS = 'Jobs/DELETEEMPLOYEE_SUCCESS';
export const DELETEEMPLOYEE_FAILURE = 'Jobs/DELETEEMPLOYEE_FAILURE';

export const DELETEEMPLOYER_SUCCESS = 'Jobs/DELETEEMPLOYER_SUCCESS';
export const DELETEEMPLOYER_FAILURE = 'Jobs/DELETEEMPLOYER_FAILURE';