export const REGISTER_SUCCESS = 'Register/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'Register/REGISTER_FAILURE';
export const REGISTER_REQUEST = 'Register/REGISTER_REQUEST';
export const RESET_REGISTER_PARAMS = 'Register/RESET_REGISTER_PARAMS';
