export const PURPOSAL_SUCCESS = 'Purposal/PURPOSAL_SUCCESS';
export const PURPOSAL_FAILURE = 'Purposal/PURPOSAL_FAILURE';
export const PURPOSAL_REQUEST = 'Purposal/PURPOSAL_REQUEST';
export const GETPURPOSALYID_SUCCESS = 'Purposal/GETPURPOSALYID_SUCCESS';
export const GETPURPOSALYID_FAILURE = 'Purposal/GETPURPOSALYID_FAILURE';
export const GETEMPLOYEEID_SUCCESS = 'Purposal/GETEMPLOYEEID_SUCCESS';
export const GETEMPLOYEEID_FAILURE = 'Purposal/GETEMPLOYEEID_FAILURE';
export const UPDATEPURPOSAL_SUCCESS = 'Purposal/UPDATEPURPOSAL_SUCCESS';
export const UPDATEPURPOSAL_FAILURE = 'Purposal/UPDATEPURPOSAL_FAILURE';

export const UPDATEONGOINGPERCENTAGE_SUCCESS = 'Purposal/UPDATEONGOINGPERCENTAGE_SUCCESS';
export const UPDATEONGOINGPERCENTAGE_FAILURE = 'Purposal/UPDATEONGOINGPERCENTAGE_FAILURE';

export const GETPURPOSALBYEMPLOYEE_SUCCESS = 'Purposal/GETPURPOSALBYEMPLOYEE_SUCCESS';
export const GETPURPOSALBYEMPLOYEE_FAILURE = 'Purposal/GETPURPOSALBYEMPLOYEE_FAILURE';

export const SUBIT_REMARKS_SUCCESS = 'Purposal/SUBIT_REMARKS_SUCCESS';
export const SUBIT_REMARKS_FAILURE = 'Purposal/SUBIT_REMARKS_FAILURE';

export const RESET_LOGIN_PARAMS = 'Login/RESET_LOGIN_PARAMS';


