export const PURPOSAL_SUCCESS = 'Purposal/PURPOSAL_SUCCESS';
export const PURPOSAL_FAILURE = 'Purposal/PURPOSAL_FAILURE';
export const PURPOSAL_REQUEST = 'Purposal/PURPOSAL_REQUEST';
export const GETPURPOSALYID_SUCCESS = 'Purposal/GETPURPOSALYID_SUCCESS';
export const GETPURPOSALYID_FAILURE = 'Purposal/GETPURPOSALYID_FAILURE';
export const GETEMPLOYEEID_SUCCESS = 'Purposal/GETEMPLOYEEID_SUCCESS';
export const GETEMPLOYEEID_FAILURE = 'Purposal/GETEMPLOYEEID_FAILURE';

export const SUBIT_REMARKS_SUCCESS = 'Purposal/SUBIT_REMARKS_SUCCESS';
export const SUBIT_REMARKS_FAILURE = 'Purposal/SUBIT_REMARKS_FAILURE';

export const RESET_LOGIN_PARAMS = 'Login/RESET_LOGIN_PARAMS';


