export const RESET_SUCCESS = 'Reset/RESET_SUCCESS';
export const RESET_FAILURE = 'Reset/RESET_FAILURE';
export const RESETEMAIL_SUCCESS = 'Reset/RESETEMAIL_SUCCESS';
export const RESETEMAIL_FAILURE = 'Reset/RESETEMAIL_FAILURE';
export const RESET_REQUEST = 'Reset/RESET_REQUEST';
export const RESET_RESET_PASSWORD_PARAMS = 'Reset/RESET_RESET_PASSWORD_PARAMS';

// RESET_RESET_PASSWORD_PARAMS