export const JOBS_SUCCESS = 'Jobs/JOBS_SUCCESS';
export const JOBS_FAILURE = 'Jobs/JOBS_FAILURE';
export const JOBS_REQUEST = 'Job/JOBS_REQUEST';
export const JOBBYID_SUCCESS = 'Jobs/JOBBYID_SUCCESS';
export const JOBBYID_FAILURE = 'Jobs/JOBBYID_FAILURE';
export const DELETEJOBS_SUCCESS = 'Jobs/DELETEJOBS_SUCCESS';
export const DELETEJOBS_FAILURE = 'Jobs/DELETEJOBS_FAILURE';
export const RESET_JOBS_PARAMS = 'Jobs/RESET_JOBS_PARAMS';
